apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-redis
  namespace: argocd

spec:
  project: default

  source:
    repoURL: "https://github.com/User210m/fastapi-redis.git"
    targetRevision: main
    path: Kubernetes

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true